### ISSUE TITLE
WebkitFontSmoothing: "antialiased",

### ISSUE THREAD

**Issue by ccorcos** [frenic/csstype#39] opened 2018-04-13 19:01 UTC
WebkitFontSmoothing: "antialiased" is a type error.

**Comment by frenic** [comment] 2018-04-13 21:29
Thank you for raising this. It's not likely that [MDN](https://github.com/mdn/data) will add this after [`font-smooth`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth) has been removed from the spec and it seems like [`-webkit-font-smoothing` isn't working as intended](https://productforums.google.com/forum/?fromgroups=#!topic/chrome/0vqp1bnkaoE) since v22. However, we're considering some kind of patching for CSSType #35 #37 to work around this. But currently I see patching as a very temporarily solution for missing properties and values until it has been fixed by MDN. But you can [fix this locally](https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors) with module augmentation or type assertion.

**Closed** 2018-04-19 09:29 UTC
Labels: wontfix
